name: Deploy backend

# on merge to dev branch
on:
    push:
        branches:
            - dev
    pull_request:
        branches:
            - dev
        types: [merged]

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up FastAPI environment
              uses: actions/setup-python@v2
              with:
                  python-version: "3.8"
            - name: Navigate to front directory and install dependencies
              run: pip install -r requirements.txt
              working-directory: ./backend/

            # Install unicorn
            - name: Install unicorn
              run: pip install uvicorn

            - name: Build application
              run: |
                  docker build -t adapt-ia-dev .
              working-directory: ./backend/
    deploy-dev:
        runs-on: ubuntu-latest
        needs: testing
        strategy:
            matrix:
                node-version: [18.x]
        steps:
            - name: executing remote ssh commands using ssh key
              uses: appleboy/ssh-action@v1.0.0
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE }}
                  port: 22
                  script: |
                      cd ~/Projects/SmartDisplay/dev_back/Adapt-IA_back
                      docker stop api-dev
                      docker rm api-dev
                      docker system prune -a
                      git pull
                      docker compose -f docker-compose.dev.yml build --no-cache
                      docker compose -f docker-compose.dev.yml up -d
