name: Build Project & Deploy

on:
    push:
        branches:
            - main
            # - richard-debug

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Set up FastAPI environment
              uses: actions/setup-python@v2
              with:
                  python-version:

            - name: Navigate to front directory and install dependencies
              run: pip install -r requirements.txt
              working-directory: ./backend/

            # - name: Run tests
            #   run: npm run test --detectOpenHandles
            #   working-directory: ./backend/app

            - name: Build application
              run: |
                  docker build -t adapt-ia-main .
              working-directory: ./backend/

    deploy:
        runs-on: ubuntu-latest
        needs: testing
        if: success()
        strategy:
            matrix:
                python-version: [3.10.0]

        steps:
            # - name: Checkout code source
            #   uses: actions/checkout@v2
            #   with:
            #     ref: main
            #     repository: Ethan-Nox/picture-manager.git
            #     token: ${{ secrets.DYLANGH }}

            # - name: Set up Docker Buildx environment
            #   uses: docker/setup-buildx-action@v1

            - name: Deploy to VPS
              uses: appleboy/ssh-action@master
              with:
                  host: ${{ secrets.SSH_HOST }}
                  username: ${{ secrets.USERNAME }}
                  key: ${{ secrets.SSH_PRIVATE }}
                  script: |
                      cd ~/Projects/SmartDisplay/back/Adapt-IA_back/
                      git pull
                      docker compose -f docker-compose.prod.yml up --build -d
