version: "3.8"

services:
  # front:
  #   container_name: front-crypto-viz
  #   stdin_open: true
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./CryptoViz_Front
  #     args:
  #       VUE_APP_API_URL: http://localhost:8080
  #   networks:
  #     - main
  #   volumes:
  #     - /CryptoViz_Front/node_modules
  #     - ./CryptoViz_Front:/CryptoViz_Front
  #   ports:
  #     - "8080:8080"
  #   image: crypto-viz_front-front:prod
  #   environment: # Vous pouvez ajouter des variables d'environnement pour configurer le hot-reloading
  #     - CHOKIDAR_USEPOLLING=true # Ceci est important pour le hot-reloading fonctionne dans certains environnements Docker
  db:
    container_name: db
    image: postgres:13-alpine
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=a8JcQ2tS5eX9mB4vF7uZ0pL6kD3xR1yW8nE6gH5j
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
      interval: 5s
      timeout: 45s
      retries: 5
    networks:
      - db
    restart: always # Ajout de l'option restart

  api:
    image: home-pedia_backend:prod
    container_name: api-prod
    build:
      context: ./HomePedia_Back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_USERNAME=postgres
      - POSTGRES_PASSWORD=a8JcQ2tS5eX9mB4vF7uZ0pL6kD3xR1yW8nE6gH5j
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
      - SECRET_KEY=ZXpmemZrLGV6ayxhYWE=
      - IS_DEV=false
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./HomePedia_Back:/app
    networks:
      - main
      - db
    restart: always # Ajout de l'option restart

networks:
  main:
    driver: bridge
  db:
    driver: bridge

volumes:
  postgres-data:
