# Generated by Django 4.2.10 on 2024-02-13 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_picture',
            field=models.ImageField(blank=True, max_length=5000000, null=True, upload_to='profile_pictures/'),
        ),
    ]
