# Generated by Django 4.2.10 on 2024-02-17 23:26

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto', '0002_cryptolike'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptolike',
            old_name='crypto',
            new_name='crypto_name',
        ),
        migrations.RenameField(
            model_name='cryptolike',
            old_name='user',
            new_name='user_id',
        ),
        migrations.AlterUniqueTogether(
            name='cryptolike',
            unique_together={('user_id', 'crypto_name')},
        ),
    ]
