# Generated by Django 4.2.10 on 2024-02-17 23:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('crypto', '0003_rename_crypto_cryptolike_crypto_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptolike',
            old_name='crypto_name',
            new_name='crypto_id',
        ),
        migrations.AlterUniqueTogether(
            name='cryptolike',
            unique_together={('user_id', 'crypto_id')},
        ),
    ]
