- name: Run the equivalent of "apt-get update" as a separate step
  ansible.builtin.apt:
    update_cache: yes

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest

- name: Install basic and required system packages
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
      - python3-pip
      - virtualenv
      - python3-setuptools
      - git
      - vim
      - rsync
      - unzip
      - wget
      - gnupg
      - python3-pip
      - pass
      - ufw
      - htop
      - acpi
      - locales
      - ansible

- name: Update all packages to their latest version
  ansible.builtin.apt:
    name: "*"
    state: latest