name: DEV - Build & Deploy SSH

on:
  pull_request:
    branches:
      - dev
    types:
      - closed
  # push:
  #   branches:
  #     - richard_redux

jobs:
  testing-dev:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 18.x

      - name: install dependencies
        run: npm install
        working-directory: ./front-react

      - name: Navigate to front directory and install dependencies
        run: docker compose -f docker-compose.dev.yml up --build -d
        working-directory: ./

  deploy-dev:
    runs-on: ubuntu-latest
    needs: testing-dev

    if: success() && github.event.pull_request.merged == true
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE }}
          port: 22
          script: |
            cd ~/Projects/SmartDisplay/dev_front/Adapt-IA_front
            docker stop front-adapt-ai-dev
            docker rm front-adapt-ai-dev
            docker system prune -a
            git pull
            docker compose --env-file ./.dev.env -f docker-compose.dev.yml build --no-cache
            docker compose --env-file ./.dev.env -f docker-compose.dev.yml up -d
