name: Testing PR

on:
  pull_request:
    types:
      - opened
    branches:
      - main
      - dev
  # push:
  #   branches:
  #     - main
  #     - dev

jobs:
  testing-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js environment
        uses: actions/setup-node@v2.4.0
        with:
          node-version: 18.x

      - name: install dependencies
        run: npm install
        working-directory: ./front-react

      - name: Create build
        run: npm run build
        working-directory: ./front-react

      - name: Launch docker compose
        run: docker compose -f docker-compose.dev.yml up --build -d
        working-directory: ./
