version: "3.8"

services:
    db:
        container_name: db
        image: postgres:13-alpine
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=a8JcQ2tS5eX9mB4vF7uZ0pL6kD3xR1yW8nE6gH5j
            - POSTGRES_DB=postgres
            - POSTGRES_PORT=5432
        volumes:
            - ./postgres-data:/var/lib/postgresql/data
        healthcheck:
            test: ["CMD", "pg_isready", "-d", "postgres", "-U", "postgres"]
            interval: 5s
            timeout: 45s
            retries: 5
        networks:
            - db

    api:
        image: adapt-ia_backend:prod
        container_name: api-prod
        build:
            context: ./backend
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        environment:
            - POSTGRES_USERNAME=postgres
            - POSTGRES_PASSWORD=a8JcQ2tS5eX9mB4vF7uZ0pL6kD3xR1yW8nE6gH5j
            - POSTGRES_DB=postgres
            - POSTGRES_PORT=5432
            - SECRET_KEY=ZXpmemZrLGV6ayxhYWE=
            - IS_DEV=false
        depends_on:
            db:
                condition: service_healthy
        volumes:
            - ./backend:/app
        networks:
            - main
            - db
        restart: always # Ajout de l'option restart

networks:
    main:
        driver: bridge
    db:
        driver: bridge

volumes:
    postgres-data:
